language: ruby
rvm:
- 2.2.2
- 2.3.7
- 2.4.4
- 2.5.1
before_install: gem install bundler
cache:
  directories:
  - vendor/bundle
install: bundle install --path=vendor/bundle
script:
- bundle exec rake spec
after_success:
- bundle exec codeclimate-test-reporter
'':
  travis:
    yml:
      secure: tdACObSxXYPTZF2DNUcHt8dzl0p+h5l+dQHsLxpfe9IdKRscaYeGYqgZ4DGjxaAAFb4bnf3Ew4JdQUOY/LOpCMDmFGkP2APDxPSHvKSRlF+2jf8ATDqOhAS3oZHlspRcdWCw1Glfz6GPwxDv5dCagH+svW2EqTDOFSyp3L6AlG8muzUCY55lw4Vxp4GrjmfOB9vimBrNrIxSYCgWSysxCba5UY8zqP9CO34RF2d04No5iSkiWBBF31NpZPxCXAa7W4ZDpQ4EkCeW7UgqfkiIT7Ht6+dFEOZFsRyMCj9x1t+ZFJEC2iKKqHRvg9eI3wuP+FpT8uBKN+5YOkJz6xqqaqWJK6vlzDUMNYTFPXin/SoENZ9YBr+USGC7wetfPdRpoMcumKFTaJA+ZpWjaHvFtr3zNle7FkzTmBZGMvwPrlt/9Mt2ouZgHp4Fj06M7JvGR/HSg7lglcm3hQll/oobE+XqJC077cmLrtVAMRDQoDA74/bn7jRRX1i+K/3LvtSWRsLmDMhw0N13vnhcdRDLXCQEFmkyDRB2jmk76HsiyTDjCQ+WC/7ZT0qeMieKE6A7vmg7YZWYxAUE3opGa+BIDw8jy1dhCZL0LX7fUDbr2OLR4qBANS5Ai+qMHmKiDYYC2993SwEX0kb12VmWwAtnLTosTSKqV7YA1n1UGM7n9wk=
