language: ruby
rvm:
  - 2.2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install: gem install bundler
cache:
  directories:
    - vendor/bundle
install: bundle install --path=vendor/bundle
script:
  - bundle exec rake spec
after_success:
  - CODECLIMATE_REPO_TOKEN=bb43f5a81bbc75fc12b8d510d664dbd90b73cdbb22adb4a0aaf7e064117687dd bundle exec codeclimate-test-reporter
