language: ruby
rvm:
  - 2.2.0
  - 2.3.0
before_install: gem install bundler -v 1.11.2
cache:
  directories:
    - vendor/bundle
install: bundle install --path=vendor/bundle
script:
    - bundle exec rake rspec
addons:
  code_climate:
    repo_token: bb43f5a81bbc75fc12b8d510d664dbd90b73cdbb22adb4a0aaf7e064117687dd
